### PR TITLE
DX-102 Updated README for code owners test

### PR DESCRIPTION
**Pull request by ecarlste**
I was able to edit the PR body text after the PR was already in the merge queue.

### CODE REVIEW

**Comment by ecarlste** [comment]
@Mergifyio refresh

**Review by lavurohit — APPROVED** [review]

**Comment by ecarlste** [comment]
@Mergifyio refresh

**Comment by ecarlste** [comment]
@TheCodeCartel/mergifytesters time to test this group!!!

**Comment by ecarlste** [comment]
@Mergifyio refresh

**Comment by ecarlste** [comment]
@mergifyio refresh

**Comment by ecarlste** [comment]
@mergify refresh

**Pull request merged**
